### ISSUE TITLE
Stuck after Cleared leases/Network is Down

### ISSUE THREAD

**Issue by NasirJAKI** [sophron/wifiphisher#280]
i have two wifi of Alfa with one antenna  and Lb-link with two antenna , but i dont know why is stoped after that point in the picter?
![s](https://cloud.githubusercontent.com/assets/19974741/16155360/b49bae00-34b7-11e6-8cea-7a1f08fe11f5.jpeg)

**Comment by sophron** [comment]
Hi @NasirJAKI,

Are you sure your VM didn't freeze for some other reason?

**Comment by NasirJAKI** [comment]
Hi @sophron,
My VMware is working OK without any issues and my two WiFi USB support AP

**Comment by NasirJAKI** [comment]
Hi @sophron
I even can write any thing after that point ....when I interned catrl + c. .. It stopped OK too

**Comment by blackHatMonkey** [comment]
@sophron 
I encounter this issue all the time. As I told you before the problem is with `scapy` module as it goes to infinite loop and won't report back.

@NasirJAKI 
Running `wifiphisher` multiple times usually solves the problem. Another method is to disconnect the network adapter chosen for the `rouge AP` and re-connect it.

**Comment by NasirJAKI** [comment]
@BlackHatMonkey
Thank you . I did it several time then it worked .. But I hope there will be a new version fixing this issue.

**Comment by abilify01** [comment]
My issue is that the output reads network down. Everything worked fine in a earlier verision of wifiphisher. I am not sure what I am doing wrong. 

wifiphisher
[*] Starting Wifiphisher 1.1GIT at 2016-06-23 00:05
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 920, in run
    sniffing(mon_iface, targeting_cb)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 209, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down


commit 1761d2c322cb5f12b1d8fd1d59a0673b11ebeb85
Kali linux 2.0
Python 2.7.12rc1

wlan2     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=14 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
lo        no wireless extensions.

wlan1     IEEE 802.11bg  ESSID:off/any  
          Mode:Monitor  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by abilify01** [comment]
I am using the following devices below.
Qualcomm Atheros AR9485 Wireless Network Adapter internal
NetGear, Inc. WG111v2 54 Mbps Wireless [RealTek RTL8187L]

Please let me know what I can do to help test these adapters. The adapters worked before in a previous version. I am not sure what version though. Thanks for all the hard work.

**Comment by blackHatMonkey** [comment]
@abilify01 
You should be able to make `wifiphisher` work if you try repeatedly for the time being. We are currently working on resolving the issue.

**Comment by abilify01** [comment]
Wifiphisher shuts down network service manager. When I try to run wifiphisher it gives me the following error. I then have to type service network-manager restart in order to get wifiphisher to try and run again. The network down issue happens when i update python-scapy through apt-get.

Kali Rolling
Python 2.7.12rc1
python-scapy (2.3.2-0.1) 
commit 1761d2c322cb5f12b1d8fd1d59a0673b11ebeb85

*] Starting Wifiphisher 1.1GIT at 2016-06-29 20:08
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/pywifiphisher.py", line 855, in run
    args.apinterface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.1-py2.7.egg/wifiphisher/interfaces.py", line 237, in __init__
    wireless_interfaces = pyric.winterfaces()
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 174, in winterfaces
    return _iostub_(winterfaces)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 1292, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 181, in winterfaces
    if iswireless(dev, iosock): wifaces.append(dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/pyw.py", line 202, in iswireless
    _ = io.io_transfer(iosock, sioch.SIOCGIWNAME, ifh.ifreq(dev))
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.2.1-py2.7.egg/pyric/lib/libio.py", line 73, in io_transfer
    raise pyric.error(e.errno,e.strerror)
pyric.error: [Errno 11] Resource temporarily unavailable

**Comment by abilify01** [comment]
I did a service network-manager restart, then unplugged my external WiFi adapter,  plugged it back in after a second,  then started wifiphisher and everything works.  I have to perform the steps listed but it works.

**Comment by wraith-wireless** [comment]
@abilify01 @blackHatMonkey you may be able to "rectify" the issue of network manager without having to shutdown/start network-manager. 

    from pyric import pyw
    # get wlan0 our jamming interface, and create a new monitor mode jam0
    wlan0 = pyw.getcard('wlan0')
    jam0 = pyw.devadd(card, 'jam0', 'monitor')
    
    # save all cards, modes on wlan0's phy for restoring later
    ifaces = pyw.ifaces
    for card, _ in ifaces:
        if card != jam0
        pyw.devdel(card)

    # execute wifiphisher

    # restore interfaces & delete the jammer
    for card, mode in ifaces:
        pyw.devadd(jam0, card.dev, mode)
     pyw.devdel(jam0) 

Network manager can continue running but it won't interfere with the jamming interface - as it's looking for the orginal card(s). It works for all my cards but an older linksys usb.

**Comment by blackHatMonkey** [comment]
@wraith-wireless 
Thanks. @sophron  and I will talk it over and hopefully implement it.

**Comment by r3cursive123** [comment]
So did we find a fix for this? I am still not able to use wifiphisher successfully on Kali Linux 2 rolling 4.0.0

**Comment by sophron** [comment]
I believe this is happening whenever the interface is not set properly to Monitor Mode. Can you update to the latest revision and let me know if the problem persists?

**Comment by pungvit** [comment]
I just test it with my own router. 
It works.. till the client target get the phising web page from fake ap ... but its warned by google security or android security system by displayed it at web..

**Comment by mehranexpert** [comment]
Same issue where is solution ?

`root@kali:~/git/wifiphisher/bin# ./wifiphisher -jI wlan1 -aI wlan2
[*] Starting Wifiphisher 1.1GIT at 2016-07-30 10:58
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>
    
  File "/root/git/wifiphisher/wifiphisher/pywifiphisher.py", line 814, in run
    sniffing(mon_iface.get_name(), targeting_cb)
  File "/root/git/wifiphisher/wifiphisher/pywifiphisher.py", line 221, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 570, in sniff
    s = L2socket(type=ETH_P_ALL, *arg, **karg)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 484, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 303, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down
root@kali:~/git/wifiphisher/bin# 
`

**Comment by mehranexpert** [comment]
ok i do this and my issue fix

`root@kali:~/git/wifiphisher/bin# ifconfig wlan1 up && ifconfig wlan2 up
`

**Comment by sophron** [comment]
@mehranexpert Thanks for reporting, I'll have a look soon.

**Comment by sophron** [comment]
I pushed a commit that makes sure that both interfaces are up.

@mehranexpert Can you check out to the latest revision and let me know if it's OK now?

**Comment by mehranexpert** [comment]
@sophron First time when i lunch wifiphisher i got error Network Down , both `wlan1` & `wlan2` go down

i must use `ifconfig wlan1 up && ifconfig wlan2 up` and try again . now Fix and wifiphisher work .

**Comment by sophron** [comment]
I believe this is now closed. Please re-open if not.

**Comment by GRA0007** [comment]
@Anaprofen and I seem to be having this same issue. It looks like it's not fixed yet. :/
