### ISSUE TITLE
Can not find module blessings

### ISSUE THREAD

**Issue by Guardius** [sophron/wifiphisher#389]
I have Kali Linux, with all updates installed.
I installed wifiphisher with the git clone command.
after install and running, here is what I get.
root@*****:~/wifiphisher# python bin/wifiphisher
Traceback (most recent call last):
  File "bin/wifiphisher", line 11, in <module>
    from wifiphisher.pywifiphisher import run
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 13, in <module>
    from blessings import Terminal
ImportError: No module named blessings

Did google search, could not find an answer, any help would be nice. Thank you. If there is something I missed that you need, please let me know.

**Comment by hg8** [comment]
`pip install blessings`

**Comment by cicina** [comment]
Dont run wifiphisher directly. 

make git clone, then cd wifiphisher
python setup.py build
python setup.py install

hopefully i got it right. cheers

**Comment by sophron** [comment]
See #386.

**Comment by foxisoft** [comment]
could you help me?
I ran the command in Kali
`root@kali:~/Desktop/wifiphisher# python setup.py build`
then
`root@kali:~/Desktop/wifiphisher# python setup.py install`
the I got this error:
_compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1_
What should I do? Thx

**Comment by anakin1028** [comment]
@foxisoft
We have fixed this can you do `python setup.py install ` again and see if it works for you?

**Comment by foxisoft** [comment]
It is OK now. It work. thanks

**Comment by foxisoft** [comment]
@anakin1028 
Sorry, but I'm m back
The above command it just executing a part of the script.
it does not ask me to install **hostapd**, I don't know why. 
Should be helpful for you to give you here all the code? Thanks for your work. 
I'm not an advanced user but still learning :1st_place_medal: 
[Foxisoft wifiphisher script errror.txt](https://github.com/wifiphisher/wifiphisher/files/1744042/Foxisoft.wifiphisher.script.errror.txt)

**Comment by anakin1028** [comment]
I'm not sure what's your problem? From the log, it looks like you have already installed roguehostapd-1.1.9 which is the newest version. 

You can do the following:
```
pip uninstall roguehostapd
python setup.py install
```
Then during the wifiphisher install process, the terminal output should tell you what shared libraries are missing so the roguehostapd build fail.

**Comment by foxisoft** [comment]
@anakin1028  I followed your directions, step-by-step, but still not working. I'm exhausted. 
I also verified the dependencies and nothing. 
See the 2 produced files below. 
If you have something more after reading the rezults....
Thanks
[Foxisoft wifiphisher script errror1.txt](https://github.com/wifiphisher/wifiphisher/files/1744893/Foxisoft.wifiphisher.script.errror1.txt)
[Foxisoft wifiphisher dependencies.txt](https://github.com/wifiphisher/wifiphisher/files/1744894/Foxisoft.wifiphisher.dependencies.txt)

**Comment by anakin1028** [comment]
Have you done with `pip uninstall roguehostapd`?
You can also do
```
cd  /usr/local/lib/python2.7/dist-packages
rm -rf roguehostapd
# back to wifiphisher folder
python setup.py install
```

**Comment by foxisoft** [comment]
@anakin1028 
done but nothing.

**Comment by anakin1028** [comment]
can you do the following:
```
pip uninstall roguehostapd
cd  /usr/local/lib/python2.7/dist-packages
ls roguehostapd*
```

can you post the terminal output? if there is nothing for the output you can install wifiphisher again.
It is strange if the tool doesn't show any warning that some of shared library is missing.

**Comment by foxisoft** [comment]
@anakin1028 
Thanks for your time. 
The terminal outputs are attached. 
[pip uninstall roguehostapd.txt](https://github.com/wifiphisher/wifiphisher/files/1748915/pip.uninstall.roguehostapd.txt)
[ls roguehostapd.txt](https://github.com/wifiphisher/wifiphisher/files/1748919/ls.roguehostapd.txt)

**Comment by anakin1028** [comment]
@foxisoft we gave uploaded a new version of roguehostapd, can you try the following:

```
pip ininstall roguehostapd
pip uninstall wifiphisher
pip install -v wifiphisher
```

And dump the output of last command for us.
Thanks!!

**Comment by foxisoft** [comment]
@anakin1028  hello there, 
I followed your directions
here are the results of all your directed commands.
Thank for your endeavor 
At least, it is a big challenge also for me and I don't want to give up until a good result. 
See you
[pip install -v wifiphisher.txt](https://github.com/wifiphisher/wifiphisher/files/1757777/pip.install.-v.wifiphisher.txt)

**Comment by anakin1028** [comment]
It looks like `pip install wifiphisher` doesn't get installed.

Can you manually purge all the wifiphisher folder under `dist-packages` and do the pip install again? And with command:
`pip install -v --no-cache wifiphihser `

**Comment by anakin1028** [comment]
Sorry I have some typos in my previous comment.

**Comment by foxisoft** [comment]
@anakin1028 
Sorry for my delay. In my country we have a lot of snow....
I did as per your directions. 
The result:
[16:49:26]\root@kali:~/Desktop/wifiphisher# pip install -v --no-cache wifiphisher
Requirement already satisfied: wifiphisher in /usr/lib/python2.7/dist-packages
Requirement already satisfied: PyRIC in /usr/lib/python2.7/dist-packages (from wifiphisher)
Cleaning up...
[16:49:52]\root@kali:~/Desktop/wifiphisher#

**Comment by anakin1028** [comment]
hey! @foxisoft I may know how to fix. Let's try again, since we have updated `roguehostapd`, we may try first to install it.

So you can try the following commands, it's a little similar as before:
```
pip uninstall roguehostapd
# make sure all the roguehostapd folders are deleted
pip install roguehostapd --no-cache -v
```

Here are my commands output:
![output](https://user-images.githubusercontent.com/6182530/36739979-2f42d280-1c1c-11e8-9406-61ec79ec115d.png)

**Comment by anakin1028** [comment]
If the commands are still not getting install roguehostapd, can you output 
```
pip --version
python --version
```

**Comment by foxisoft** [comment]
hello again @anakin1028 
I did your commands. Here are the results:
<pre>[17:03:41]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~</b></font># pip uninstall roguehostapd
<font color="#CC0000">Cannot uninstall requirement roguehostapd, not installed</font>
</pre>
and 
<pre>[10:51:11]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># pip install roguehostapd --no-cache
Collecting roguehostapd
  Downloading roguehostapd-1.2.2.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 1.8MB/s 
Installing collected packages: roguehostapd
  Running setup.py install for roguehostapd ... done
Successfully installed roguehostapd-1.2.2
[10:52:26]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># 
</pre>
and 
<pre>[10:52:26]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
[10:54:45]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># 
</pre>
and 
[10:54:45]\root@kali:~/Desktop/wifiphisher# python --version
Python 2.7.14+
[10:55:17]\root@kali:~/Desktop/wifiphisher# 
Seems to be like in your terminal in the image you sent 
Should I run `python setup.py install
Thanks`

**Comment by anakin1028** [comment]
This looks good. You can just run wifiphisher now, and see if the tool works for you!

**Comment by foxisoft** [comment]
@anakin1028 
The same result
<pre>[11:05:32]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info/requires.txt
writing wifiphisher.egg-info/PKG-INFO
writing top-level names to wifiphisher.egg-info/top_level.txt
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
reading manifest file &apos;wifiphisher.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
writing manifest file &apos;wifiphisher.egg-info/SOURCES.txt&apos;
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-known-open-wlans -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-mac-prefixes -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/dinosaur.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/chrome-offline.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/mac-network-manager.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/loading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/wifi-icon.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/win-behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/dinosaur.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/chrome-offline.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/mac-network-manager.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/wifi-icon.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/win-behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/question.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/question.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/update/update.exe -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/favicon.ico -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/plugins.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/jquery.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/theme.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/update/update.exe -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/favicon.ico -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/plugins.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/jquery.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/theme.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/loading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/upgrading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.svg -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/FontAwesome.otf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2 -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.eot -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/js/index.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/js/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/license.txt -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/oauth.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/reset.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/roboto.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/index.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/reset.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/roboto.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/cert
copying build/lib.linux-x86_64-2.7/wifiphisher/data/cert/server.pem -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/cert
creating build/bdist.linux-x86_64/egg/wifiphisher/data/locs
copying build/lib.linux-x86_64-2.7/wifiphisher/data/locs/.gitkeep -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/locs
creating build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/knownbeacons.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/wpspbc.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/handshakeverify.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/lure10.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/deauth.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/pywifiphisher.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/extensions.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/recon.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/firewall.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/uimethods.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishingpage.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/constants.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/opmode.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/interfaces.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishinghttp.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/accesspoint.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/tui.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/macmatcher.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/knownbeacons.py to knownbeacons.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/wpspbc.py to wpspbc.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/handshakeverify.py to handshakeverify.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/lure10.py to lure10.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/deauth.py to deauth.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/extensions.py to extensions.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/recon.py to recon.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/firewall.py to firewall.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/uimethods.py to uimethods.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishingpage.py to phishingpage.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/opmode.py to opmode.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/interfaces.py to interfaces.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishinghttp.py to phishinghttp.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/accesspoint.py to accesspoint.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/tui.py to tui.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/macmatcher.py to macmatcher.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.constants: module references __file__
creating &apos;dist/wifiphisher-1.4-py2.7.egg&apos; and adding &apos;build/bdist.linux-x86_64/egg&apos; to it
removing &apos;build/bdist.linux-x86_64/egg&apos; (and everything under it)
Processing wifiphisher-1.4-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Extracting wifiphisher-1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding wifiphisher 1.4 to easy-install.pth file
Installing wifiphisher script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for tornado==4.5.3
Best match: tornado 4.5.3
Adding tornado 4.5.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for scapy==2.3.3
Best match: scapy 2.3.3
Adding scapy 2.3.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for roguehostapd==1.2.2
Best match: roguehostapd 1.2.2
Adding roguehostapd 1.2.2 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for pbkdf2==1.3
Best match: pbkdf2 1.3
Processing pbkdf2-1.3-py2.7.egg
pbkdf2 1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pbkdf2-1.3-py2.7.egg
Searching for dbus-python==1.2.4
Best match: dbus-python 1.2.4
Processing dbus_python-1.2.4-py2.7-linux-x86_64.egg
dbus-python 1.2.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-x86_64.egg
Searching for PyRIC==0.1.5
Best match: PyRIC 0.1.5
Adding PyRIC 0.1.5 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for wifiphisher==1.4

                     _  __ _       _     _     _               
                    (_)/ _(_)     | |   (_)   | |              
  ((.))    __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __ 
    |      \ \ /\ / / |  _| | &apos;_ \| &apos;_ \| / __| &apos;_ \ / _ \ &apos;__|
   /_\      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |   
  /___\      \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|   
 /     \                    | |                                
                            |_|                                
                                                               
[12:04:52]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># </pre>

**Comment by anakin1028** [comment]
This means roguehostapd has been installed. You can just run `python bin/wifiphisher` and start using tool~~

**Comment by anakin1028** [comment]
Before I wanted you reinstall roguehostapd is because that I'm not sure you have installed the latest version(there are bugs in the previous version). With the argument `--no-cache` we can force pip not use the cache in your local system but to download the package in PyPI server.

**Comment by foxisoft** [comment]
@anakin1028 
Now I got other error:
<pre>[12:21:19]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># pip install roguehostapd --no-cache -v
Requirement already satisfied: roguehostapd in /usr/local/lib/python2.7/dist-packages
Cleaning up...
[12:21:51]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># python bin/wifiphisher
Traceback (most recent call last):
  File &quot;bin/wifiphisher&quot;, line 16, in &lt;module&gt;
    from wifiphisher.pywifiphisher import run
  File &quot;/root/Desktop/wifiphisher/wifiphisher/pywifiphisher.py&quot;, line 25, in &lt;module&gt;
    import wifiphisher.common.interfaces as interfaces
  File &quot;/root/Desktop/wifiphisher/wifiphisher/common/interfaces.py&quot;, line 11, in &lt;module&gt;
    import dbus
ImportError: No module named dbus
[12:22:38]\<font color="#CC0000"><b>root@kali</b></font>:<font color="#3465A4"><b>~/Desktop/wifiphisher</b></font># 
</pre>

**Comment by anakin1028** [comment]
can you try `apt-get install python-dbus`

**Comment by foxisoft** [comment]
I believe now is OK.
It starts the software
first it shows this
<pre>[<font color="#FCE94F">*</font>] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-02-28 13:06
[<font color="#4E9A06">+</font>] Selecting <font color="#4E9A06">wlan1</font> interface for the deauthentication attack
[<font color="#4E9A06">+</font>] Selecting <font color="#4E9A06">wlan0</font> interface for creating the rogue Access Point
[<font color="#4E9A06">+</font>] Sending SIGKILL to wpa_supplicant
[<font color="#4E9A06">+</font>] Sending SIGKILL to dhclient
[<font color="#4E9A06">+</font>] Sending SIGKILL to NetworkManager
[<font color="#4E9A06">+</font>] Changing wlan0 MAC addr (BSSID) to 00:00:00:3d:0f:ed
[<font color="#4E9A06">+</font>] Changing wlan1 MAC addr to 00:00:00:1f:db:36
[<font color="#FCE94F">*</font>] Cleared leases, started DHCP, set up iptables
[<font color="#4E9A06">+</font>] Show your support!
[<font color="#4E9A06">+</font>] Follow us: https://twitter.com/wifiphisher
[<font color="#4E9A06">+</font>] Like us: https://www.facebook.com/Wifiphisher
[<font color="#4E9A06">+</font>] Captured credentials:
</pre>
then 
<pre><span style="background-color:#2E3436"><font color="#D3D7CF">   Options:  [Esc] Quit  [Up Arrow] Move Up  [Down Arrow] Move Down</font></span>

<span style="background-color:#2E3436"><font color="#D3D7CF">     ESSID                          BSSID            CH  PWR  ENCR      CLIENTS VENDOR</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   ┌────────────────────────────────────────────────────────────────────────────────────────────────────┐</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ </font></span><span style="background-color:#06989A"><font color="#2E3436">foxisoft-2.4G                  80:8c:97:2f:9e:ea 11 100%  WPA2     0   Unknown             </font></span><span style="background-color:#2E3436"><font color="#D3D7CF">        │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ Carmen                         10:be:f5:26:4a:6c 2  100% WPA2/WPS   0   Unknown                    │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ TP-LINK_DC62                   50:c7:bf:20:dc:62 6   94% WPA/WPS   0   Tp-link Technologies        │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ andra                          64:66:b3:f7:cb:42 7   86% WPA2/WPS   0   Tp-link Technologies       │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ DIGI-24-30D8EB                 80:8c:97:30:d8:eb 4   84%  WPA2     0   Unknown                     │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ Samsung                        c8:3a:35:08:9f:80 7   80%   WPA     0   Tenda Technology            │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ Home                           44:d9:e7:03:0a:ff 6   76% WPA2/WPS   0   Ubiquiti Networks          │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ Aura                           58:6d:8f:78:08:63 5   72%  WPA2     0   Cisco-Linksys               │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ D-Link_MAN                     c0:a0:bb:8d:17:c7 2   70% WPA2/WPS   0   D-Link International       │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ DIGI-24-2EEBFD                 80:8c:97:2e:eb:fd 3   70%  WPA2     0   Unknown                     │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ Home                           44:d9:e7:03:09:c6 6   70% WPA2/WPS   0   Ubiquiti Networks          │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ zahar                          10:fe:ed:de:ba:fc 6   70% WPA2/WPS   0   Tp-link Technologies       │</font></span>
<span style="background-color:#2E3436"><font color="#D3D7CF">   │ alex                           f8:d1:11:a4:03:b2 6   70% WPA2/WPS   0   Tp-link Technologies  </font></span></pre>
It displays the wifi network in my area. 
I believe now is ok to use it
Thanks for all, you are great!
Now, if you can help me with some "light" information
- do you know how can I restart the wifi card after using wifiphisher? I saw that I wasn't able to use the net because, after starting and stopping the wifiphisher, the wifi card was down
Thanks

**Comment by anakin1028** [comment]
Sure. You can use
`service network-manager restart` to restart the wifiphisher~

**Comment by foxisoft** [comment]
and another one:
could you provide me your (or a valid) sources.list. I had a non functioning one, edited by me with a lot of stuffs giving me some errors during upgrade-update. 
Thanks

**Comment by usama7628674** [comment]
copy these lines to your sources.list 
`deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free`

**Comment by foxisoft** [comment]
👍
